import { Montserrat } from "next/font/google";

import { Navbar } from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { Stats } from "@/components/Stats";

import "./globals.css";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "H&H Power",
  description: "Generated by create next app",
  icons: [
    {
      url: "/logo.png",
      href: "/logo.png",
    },
  ],
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${monsterrat.className} h-full`}>
        <Navbar />
        <main className="pt-32">{children}</main>
        <Stats />
        <Footer />
      </body>
    </html>
  );
}
